from pathlib import Path

import pytest
from pyshacl import validate
from rdflib import Graph


ROOT = Path(__file__).resolve().parents[1]


def load(pattern: str) -> Graph:
    graph = Graph()
    for path in sorted(ROOT.glob(pattern)):
        graph.parse(path, format="turtle")
    return graph


PREFIXES = """
@prefix ex: <https://example.org/invalid/> .
@prefix modavis: <https://w3id.org/modavis/ontology/core#> .
@prefix modassert: <https://w3id.org/modavis/ontology/assertion#> .
@prefix modaudio: <https://w3id.org/modavis/ontology/audio#> .
@prefix modcontext: <https://w3id.org/modavis/ontology/context#> .
@prefix modevent: <https://w3id.org/modavis/ontology/events#> .
@prefix modevidence: <https://w3id.org/modavis/ontology/evidence#> .
@prefix modinst: <https://w3id.org/modavis/ontology/instrument#> .
@prefix modheritage: <https://w3id.org/modavis/ontology/heritage#> .
@prefix modmedia: <https://w3id.org/modavis/ontology/media#> .
@prefix modmidi: <https://w3id.org/modavis/ontology/midi#> .
@prefix modorgan: <https://w3id.org/modavis/ontology/organ#> .
@prefix modvmi: <https://w3id.org/modavis/ontology/virtual-instrument#> .
@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix assertionpredicate: <https://w3id.org/modavis/vocab/assertion-predicate/> .
@prefix assertionstatus: <https://w3id.org/modavis/vocab/assertion-status/> .
@prefix compatstatus: <https://w3id.org/modavis/vocab/compatibility-status/> .
@prefix eventtype: <https://w3id.org/modavis/vocab/event-type/> .
@prefix insttype: <https://w3id.org/modavis/vocab/instrument-type/> .
@prefix membership: <https://w3id.org/modavis/vocab/component-membership-type/> .
@prefix role: <https://w3id.org/modavis/vocab/functional-role/> .
@prefix vmisource: <https://w3id.org/modavis/vocab/virtual-instrument-source-relation/> .
@prefix vmiproduction: <https://w3id.org/modavis/vocab/virtual-instrument-production-method/> .
@prefix checksum: <https://w3id.org/modavis/vocab/checksum-algorithm/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
"""


CASES = [
    ("managed resource non-HTTPS identity", "<urn:uuid:00000000-0000-0000-0000-000000000001> a modavis:MODAVISManagedResource .", "requires a stable https identity"),
    ("identifier missing scheme", 'ex:id a modavis:Identifier ; modavis:identifierValue "local-1" .', "requires exactly one identified assigning scheme"),
    ("duplicate canonical label language", 'ex:r a modavis:IdentifiedResource ; modavis:canonicalLabel "First"@en, "Second"@en .', "uniquelangconstraintcomponent"),
    ("empty raw temporal expression", 'ex:t a modavis:TimeSpan ; modavis:rawTemporalExpression "" .', "must be a non-empty string"),
    ("mixed time boundary", 'ex:t a modavis:TimeSpan ; modavis:startDate "2026-01-01"^^xsd:date ; modavis:endDateTime "2026-01-02T00:00:00Z"^^xsd:dateTime .', "must not mix"),
    ("timezone-less time boundary", 'ex:t a modavis:TimeSpan ; modavis:startDateTime "2026-01-01T00:00:00"^^xsd:dateTime .', "must include a timezone"),
    ("instrument state multiple extents", 'ex:i a modinst:MusicalInstrument ; modinst:instrumentType insttype:violin . ex:t1 a modavis:TimeSpan ; modavis:rawTemporalExpression "first" . ex:t2 a modavis:TimeSpan ; modavis:rawTemporalExpression "second" . ex:s a modinst:InstrumentState ; modinst:stateOf ex:i ; modavis:validDuring ex:t1, ex:t2 .', "requires exactly one temporal extent"),
    ("instrument identity collapse", 'ex:x a modinst:MusicalInstrument, modinst:InstrumentState ; modinst:instrumentType insttype:violin ; modinst:stateOf ex:x ; modavis:validDuring ex:t . ex:t a modavis:TimeSpan ; modavis:rawTemporalExpression "unknown" .', "cannot occupy more than one of the distinct musical-instrument"),
    ("membership self", "ex:m a modinst:ComponentMembership ; modinst:parentComponent ex:c ; modinst:childComponent ex:c .", "cannot relate a component to itself"),
    ("membership configuration mismatch", "ex:i a modinst:MusicalInstrument ; modinst:instrumentType insttype:violin . ex:other a modinst:MusicalInstrument ; modinst:instrumentType insttype:violin . ex:c a modinst:InstrumentComponent . ex:cfg a modinst:InstrumentConfiguration ; modinst:configurationOf ex:other . ex:m a modinst:ComponentMembership ; modinst:membershipInstrument ex:i ; modinst:childComponent ex:c ; modinst:membershipType membership:structural-part ; modinst:appliesInConfiguration ex:cfg .", "configuration must belong to the membership instrument"),
    ("membership state mismatch", 'ex:i a modinst:MusicalInstrument ; modinst:instrumentType insttype:violin . ex:other a modinst:MusicalInstrument ; modinst:instrumentType insttype:violin . ex:c a modinst:InstrumentComponent . ex:t a modavis:TimeSpan ; modavis:rawTemporalExpression "unknown" . ex:s a modinst:InstrumentState ; modinst:stateOf ex:other ; modavis:validDuring ex:t . ex:m a modinst:ComponentMembership ; modinst:membershipInstrument ex:i ; modinst:childComponent ex:c ; modinst:membershipType membership:structural-part ; modinst:appliesInState ex:s .', "state must describe the membership instrument"),
    ("membership discovery owner mismatch", "ex:i a modinst:MusicalInstrument ; modinst:instrumentType insttype:violin ; modinst:hasMembership ex:m . ex:other a modinst:MusicalInstrument ; modinst:instrumentType insttype:violin . ex:c a modinst:InstrumentComponent . ex:m a modinst:ComponentMembership ; modinst:membershipInstrument ex:other ; modinst:childComponent ex:c ; modinst:membershipType membership:structural-part .", "discovery link must originate from the membership instrument or recorded parent component"),
    ("configuration discovery owner mismatch", "ex:i a modinst:MusicalInstrument ; modinst:instrumentType insttype:violin ; modinst:hasConfiguration ex:cfg . ex:other a modinst:MusicalInstrument ; modinst:instrumentType insttype:violin . ex:cfg a modinst:InstrumentConfiguration ; modinst:configurationOf ex:other .", "hasconfiguration link must originate from the configuration's instrument or from a state of that instrument"),
    ("functional role state configuration mismatch", 'ex:i a modinst:MusicalInstrument ; modinst:instrumentType insttype:violin . ex:other a modinst:MusicalInstrument ; modinst:instrumentType insttype:violin . ex:t a modavis:TimeSpan ; modavis:rawTemporalExpression "unknown" . ex:s a modinst:InstrumentState ; modinst:stateOf ex:i ; modavis:validDuring ex:t . ex:cfg a modinst:InstrumentConfiguration ; modinst:configurationOf ex:other . ex:c a modinst:InstrumentComponent . ex:r a modinst:FunctionalRoleAssignment ; modinst:roleOfComponent ex:c ; modinst:assignedRole role:resonator ; modinst:appliesInState ex:s ; modinst:appliesInConfiguration ex:cfg .', "state and configuration qualifiers must concern the same musical instrument"),
    ("unknown membership type", "ex:i a modinst:MusicalInstrument ; modinst:instrumentType insttype:violin . ex:c a modinst:InstrumentComponent . ex:m a modinst:ComponentMembership ; modinst:membershipInstrument ex:i ; modinst:childComponent ex:c ; modinst:membershipType ex:unknown .", "inconstraintcomponent"),
    ("unknown functional role", "ex:c a modinst:InstrumentComponent . ex:r a modinst:FunctionalRoleAssignment ; modinst:roleOfComponent ex:c ; modinst:assignedRole ex:unknown .", "inconstraintcomponent"),
    ("coupler self", "ex:c a modorgan:OrganCoupler ; modorgan:couplesFrom ex:x ; modorgan:couplesTo ex:x .", "must connect distinct components"),
    ("representation cycle", "ex:a a modmedia:Representation ; modmedia:representationOf ex:b . ex:b a modmedia:Representation ; modmedia:representationOf ex:a .", "cannot contain a cycle"),
    ("digital asset derivation cycle", "ex:a a modmedia:DigitalAsset ; modmedia:derivedFrom ex:b . ex:b a modmedia:DigitalAsset ; modmedia:derivedFrom ex:a .", "derivation chain cannot contain a cycle"),
    ("region past signal", 'ex:s a modaudio:AudioSignal ; modaudio:sampleRate "1.0"^^xsd:decimal ; modaudio:channelCount "2"^^xsd:positiveInteger ; modaudio:totalFrames "100"^^xsd:positiveInteger . ex:r a modaudio:SignalRegion ; modaudio:appliesToSignal ex:s ; modaudio:startFrameInclusive "0"^^xsd:nonNegativeInteger ; modaudio:endFrameExclusive "101"^^xsd:positiveInteger .', "cannot exceed the fixed signal's total"),
    ("release past signal", 'ex:s a modaudio:AudioSignal ; modaudio:sampleRate "1.0"^^xsd:decimal ; modaudio:channelCount "2"^^xsd:positiveInteger ; modaudio:totalFrames "100"^^xsd:positiveInteger . ex:r a modaudio:SignalRegion ; modaudio:appliesToSignal ex:s ; modaudio:startFrameInclusive "0"^^xsd:nonNegativeInteger ; modaudio:endFrameExclusive "10"^^xsd:positiveInteger ; modaudio:releaseStartFrame "101"^^xsd:nonNegativeInteger .', "release start frame cannot exceed"),
    ("release before region", 'ex:s a modaudio:AudioSignal ; modaudio:sampleRate "1.0"^^xsd:decimal ; modaudio:channelCount "1"^^xsd:positiveInteger ; modaudio:totalFrames "100"^^xsd:positiveInteger . ex:r a modaudio:SignalRegion ; modaudio:appliesToSignal ex:s ; modaudio:startFrameInclusive "20"^^xsd:nonNegativeInteger ; modaudio:endFrameExclusive "30"^^xsd:positiveInteger ; modaudio:releaseStartFrame "19"^^xsd:nonNegativeInteger .', "cannot precede its inclusive start"),
    ("channel past signal", 'ex:s a modaudio:AudioSignal ; modaudio:sampleRate "1.0"^^xsd:decimal ; modaudio:channelCount "2"^^xsd:positiveInteger ; modaudio:totalFrames "100"^^xsd:positiveInteger . ex:r a modaudio:SignalRegion ; modaudio:appliesToSignal ex:s ; modaudio:startFrameInclusive "0"^^xsd:nonNegativeInteger ; modaudio:endFrameExclusive "10"^^xsd:positiveInteger ; modaudio:referenceChannelIndex "2"^^xsd:nonNegativeInteger .', "reference-channel index must be smaller"),
    ("crossfade past loop", 'ex:s a modaudio:AudioSignal ; modaudio:sampleRate "1.0"^^xsd:decimal ; modaudio:channelCount "1"^^xsd:positiveInteger ; modaudio:totalFrames "100"^^xsd:positiveInteger . ex:r a modaudio:SustainLoopRegion ; modaudio:appliesToSignal ex:s ; modaudio:startFrameInclusive "10"^^xsd:nonNegativeInteger ; modaudio:endFrameExclusive "20"^^xsd:positiveInteger ; modaudio:crossfadeFrames "11"^^xsd:nonNegativeInteger .', "crossfade cannot be longer"),
    ("loop signal mismatch", 'ex:s1 a modaudio:AudioSignal ; modaudio:sampleRate "1.0"^^xsd:decimal ; modaudio:channelCount "1"^^xsd:positiveInteger ; modaudio:totalFrames "100"^^xsd:positiveInteger . ex:s2 a modaudio:AudioSignal ; modaudio:sampleRate "1.0"^^xsd:decimal ; modaudio:channelCount "1"^^xsd:positiveInteger ; modaudio:totalFrames "100"^^xsd:positiveInteger . ex:r a modaudio:SustainLoopRegion ; modaudio:appliesToSignal ex:s2 ; modaudio:startFrameInclusive "10"^^xsd:nonNegativeInteger ; modaudio:endFrameExclusive "20"^^xsd:positiveInteger . ex:l a modaudio:LoopPointSet ; modaudio:appliesToSignal ex:s1 ; modaudio:hasLoopRegion ex:r .', "must use the same fixed audio signal"),
    ("playback loop sample mismatch", 'ex:s1 a modaudio:AudioSample ; modaudio:sampleRate "1.0"^^xsd:decimal ; modaudio:channelCount "1"^^xsd:positiveInteger ; modaudio:totalFrames "100"^^xsd:positiveInteger . ex:s2 a modaudio:AudioSignal ; modaudio:sampleRate "1.0"^^xsd:decimal ; modaudio:channelCount "1"^^xsd:positiveInteger ; modaudio:totalFrames "100"^^xsd:positiveInteger . ex:r a modaudio:SustainLoopRegion ; modaudio:appliesToSignal ex:s2 ; modaudio:startFrameInclusive "10"^^xsd:nonNegativeInteger ; modaudio:endFrameExclusive "20"^^xsd:positiveInteger . ex:l a modaudio:LoopPointSet ; modaudio:appliesToSignal ex:s2 ; modaudio:hasLoopRegion ex:r . ex:p a modaudio:SamplePlaybackParameters ; modaudio:playsSample ex:s1 ; modaudio:usesLoopPointSet ex:l .', "must apply to the sample being played"),
    ("playback release sample mismatch", 'ex:s1 a modaudio:AudioSample ; modaudio:sampleRate "1.0"^^xsd:decimal ; modaudio:channelCount "1"^^xsd:positiveInteger ; modaudio:totalFrames "100"^^xsd:positiveInteger . ex:s2 a modaudio:AudioSignal ; modaudio:sampleRate "1.0"^^xsd:decimal ; modaudio:channelCount "1"^^xsd:positiveInteger ; modaudio:totalFrames "100"^^xsd:positiveInteger . ex:r a modaudio:ReleaseRegion ; modaudio:appliesToSignal ex:s2 ; modaudio:startFrameInclusive "10"^^xsd:nonNegativeInteger ; modaudio:endFrameExclusive "20"^^xsd:positiveInteger . ex:p a modaudio:SamplePlaybackParameters ; modaudio:playsSample ex:s1 ; modaudio:usesReleaseRegion ex:r .', "release region selected for playback"),
    ("midi note range", 'ex:p a modaudio:SamplePlaybackParameters ; modaudio:playsSample ex:s . ex:s a modaudio:AudioSample ; modaudio:sampleRate "1.0"^^xsd:decimal ; modaudio:channelCount "1"^^xsd:positiveInteger ; modaudio:totalFrames "1"^^xsd:positiveInteger . ex:b a modmidi:MidiPlaybackBinding ; modmidi:playbackParameters ex:p ; modmidi:rootNoteNumber "60"^^xsd:nonNegativeInteger ; modmidi:minimumNoteNumber "70"^^xsd:nonNegativeInteger ; modmidi:maximumNoteNumber "60"^^xsd:nonNegativeInteger .', "range cannot have a minimum greater"),
    ("midi root range", 'ex:p a modaudio:SamplePlaybackParameters ; modaudio:playsSample ex:s . ex:s a modaudio:AudioSample ; modaudio:sampleRate "1.0"^^xsd:decimal ; modaudio:channelCount "1"^^xsd:positiveInteger ; modaudio:totalFrames "1"^^xsd:positiveInteger . ex:b a modmidi:MidiPlaybackBinding ; modmidi:playbackParameters ex:p ; modmidi:rootNoteNumber "50"^^xsd:nonNegativeInteger ; modmidi:minimumNoteNumber "60"^^xsd:nonNegativeInteger .', "root midi note number must fall"),
    ("midi velocity range", 'ex:p a modaudio:SamplePlaybackParameters ; modaudio:playsSample ex:s . ex:s a modaudio:AudioSample ; modaudio:sampleRate "1.0"^^xsd:decimal ; modaudio:channelCount "1"^^xsd:positiveInteger ; modaudio:totalFrames "1"^^xsd:positiveInteger . ex:b a modmidi:MidiPlaybackBinding ; modmidi:playbackParameters ex:p ; modmidi:rootNoteNumber "60"^^xsd:nonNegativeInteger ; modmidi:minimumNoteOnVelocity "100"^^xsd:nonNegativeInteger ; modmidi:maximumNoteOnVelocity "20"^^xsd:nonNegativeInteger .', "velocity range cannot have"),
    ("midi zero note-on velocity", 'ex:p a modaudio:SamplePlaybackParameters ; modaudio:playsSample ex:s . ex:s a modaudio:AudioSample ; modaudio:sampleRate "1.0"^^xsd:decimal ; modaudio:channelCount "1"^^xsd:positiveInteger ; modaudio:totalFrames "1"^^xsd:positiveInteger . ex:b a modmidi:MidiPlaybackBinding ; modmidi:playbackParameters ex:p ; modmidi:rootNoteNumber "60"^^xsd:nonNegativeInteger ; modmidi:minimumNoteOnVelocity "0"^^xsd:nonNegativeInteger .', "velocity zero denotes note-off"),
    ("tuning target xone", 'ex:e a modaudio:TuningEntry ; modaudio:soundingComponent ex:c ; modaudio:logicalControl ex:k ; modaudio:targetFrequencyHz "440.0"^^xsd:decimal .', "xoneconstraintcomponent"),
    ("assertion evidence mismatch", 'ex:a a modassert:Assertion ; modassert:assertsSubject ex:s ; modassert:assertsPredicate assertionpredicate:has-builder ; modassert:assertsObject ex:o ; modassert:assertionStatus assertionstatus:accepted ; modassert:hasEvidenceRelation ex:e . ex:e a modevidence:EvidenceRelation ; modevidence:evaluates ex:other .', "must identify that assertion"),
    ("builder assertion literal object", 'ex:i a modinst:MusicalInstrument ; modinst:instrumentType insttype:violin . ex:a a modassert:Assertion ; modassert:assertsSubject ex:i ; modassert:assertsPredicate assertionpredicate:has-builder ; modassert:assertsLiteral "Unknown builder" ; modassert:assertionStatus assertionstatus:draft .', "requires an identified agent object"),
    ("assertion supersession cycle", 'ex:a a modassert:Assertion ; modassert:supersedes ex:a .', "supersession chain cannot contain a cycle"),
    ("evidence relation multiple targets", 'ex:r a modevidence:EvidenceRelation ; modevidence:evaluates ex:a, ex:b .', "evaluates exactly one identified target"),
    ("projection value mismatch", 'ex:a a modassert:Assertion ; modassert:assertsSubject ex:s ; modassert:assertsPredicate assertionpredicate:has-builder ; modassert:assertsObject ex:o . ex:p a modassert:Projection ; modassert:projectsAssertion ex:a ; modassert:projectionSubject ex:wrong ; modassert:projectionPredicateIri "https://w3id.org/modavis/ontology/instrument#hasBuilder"^^xsd:anyURI ; modassert:projectionObject ex:o ; modassert:projectionRule ex:r ; modassert:projectionRuleVersion "1" ; modassert:projectionGeneratedBy ex:g .', "must reproduce the assertion"),
    ("projection predicate mismatch", 'ex:a a modassert:Assertion ; modassert:assertsSubject ex:s ; modassert:assertsPredicate assertionpredicate:has-builder ; modassert:assertsObject ex:o . ex:p a modassert:Projection ; modassert:projectsAssertion ex:a ; modassert:projectionSubject ex:s ; modassert:projectionPredicateIri "https://example.org/wrong"^^xsd:anyURI ; modassert:projectionObject ex:o ; modassert:projectionRule ex:r ; modassert:projectionRuleVersion "1" ; modassert:projectionGeneratedBy ex:g .', "predicate iri must equal"),
    ("projection relative predicate IRI", 'ex:a a modassert:Assertion ; modassert:assertsSubject ex:s ; modassert:assertsPredicate assertionpredicate:has-builder ; modassert:assertsObject ex:o . ex:p a modassert:Projection ; modassert:projectsAssertion ex:a ; modassert:projectionSubject ex:s ; modassert:projectionPredicateIri "relative-property"^^xsd:anyURI ; modassert:projectionObject ex:o ; modassert:projectionRule ex:r ; modassert:projectionRuleVersion "1" ; modassert:projectionGeneratedBy ex:g .', "patternconstraintcomponent"),
    ("projection from nonaccepted assertion", 'ex:a a modassert:Assertion ; modassert:assertsSubject ex:s ; modassert:assertsPredicate assertionpredicate:has-builder ; modassert:assertsObject ex:o ; modassert:assertionStatus assertionstatus:rejected . ex:p a modassert:Projection ; modassert:projectsAssertion ex:a ; modassert:projectionSubject ex:s ; modassert:projectionPredicateIri "https://w3id.org/modavis/ontology/instrument#hasBuilder"^^xsd:anyURI ; modassert:projectionObject ex:o ; modassert:projectionRule ex:r ; modassert:projectionRuleVersion "1" ; modassert:projectionGeneratedBy ex:g .', "hasvalueconstraintcomponent"),
    ("projection missing materialization locus", 'ex:i a modinst:MusicalInstrument ; modinst:instrumentType insttype:violin . ex:o a modavis:Person . ex:a a modassert:Assertion ; modassert:assertsSubject ex:i ; modassert:assertsPredicate assertionpredicate:has-builder ; modassert:assertsObject ex:o ; modassert:assertionStatus assertionstatus:accepted . ex:p a modassert:Projection ; modassert:projectsAssertion ex:a ; modassert:projectionSubject ex:i ; modassert:projectionPredicateIri "https://w3id.org/modavis/ontology/instrument#hasBuilder"^^xsd:anyURI ; modassert:projectionObject ex:o ; modassert:projectionRule ex:r ; modassert:projectionRuleVersion "1" ; modassert:projectionGeneratedBy ex:g .', "without a named target graph must include its exact projected rdf statement"),
    ("conflict missing criterion", 'ex:a1 a modassert:Assertion . ex:a2 a modassert:Assertion . ex:c a modassert:ConflictSet ; modassert:hasConflictMember ex:a1, ex:a2 .', "requires one identified criterion"),
    ("conflict choice not member", 'ex:a1 a modassert:Assertion . ex:a2 a modassert:Assertion . ex:c a modassert:ConflictSet ; modassert:hasConflictMember ex:a1, ex:a2 . ex:d a modassert:ConflictDecision ; modassert:decisionFor ex:c ; modassert:chosenAssertion ex:other ; modassert:decidedBy ex:editor ; modassert:decisionRationale "invalid choice" . ex:other a modassert:Assertion .', "chosen assertion must be a member"),
    ("snapshot compact hash only", 'ex:s a modevidence:SourceSnapshot ; modevidence:snapshotOf ex:r ; modevidence:contentHash "sha256:0000" . ex:r a modevidence:SourceResource .', "requires exactly one qualified checksum"),
    ("snapshot duplicate checksums", 'ex:s a modevidence:SourceSnapshot ; modevidence:snapshotOf ex:r ; modevidence:hasChecksum ex:c1, ex:c2 . ex:r a modevidence:SourceResource .', "requires exactly one qualified checksum"),
    ("source snapshot timezone-less capture", 'ex:s a modevidence:SourceSnapshot ; modevidence:snapshotOf ex:r ; modevidence:hasChecksum ex:c ; modevidence:snapshotCapturedAt "2026-08-27T12:00:00"^^xsd:dateTime ; modevidence:snapshotCapturedBy ex:a . ex:r a modevidence:SourceResource . ex:c a modevidence:Checksum ; modevidence:checksumAlgorithm checksum:sha-256 ; modevidence:checksumValue "0000000000000000000000000000000000000000000000000000000000000000" . ex:a a prov:Activity .', "timezone-qualified xsd:datetime capture instant"),
    ("source snapshot missing generating activity", 'ex:s a modevidence:SourceSnapshot ; modevidence:snapshotOf ex:r ; modevidence:hasChecksum ex:c ; modevidence:snapshotCapturedAt "2026-08-27T12:00:00Z"^^xsd:dateTime . ex:r a modevidence:SourceResource . ex:c a modevidence:Checksum ; modevidence:checksumAlgorithm checksum:sha-256 ; modevidence:checksumValue "0000000000000000000000000000000000000000000000000000000000000000" .', "accountable generating activity"),
    ("unknown checksum algorithm", 'ex:c a modevidence:Checksum ; modevidence:checksumAlgorithm ex:unknown ; modevidence:checksumValue "0000" .', "closed release scheme"),
    ("selector without interpretation model", 'ex:s a modevidence:Selector ; modevidence:selectorValue "page=1" .', "selector requires a non-empty value"),
    ("relative source URI", 'ex:s a modevidence:SourceResource ; modevidence:sourceUri "relative/path"^^xsd:anyURI .', "patternconstraintcomponent"),
    ("parameter set compact hash only", 'ex:p a <https://w3id.org/modavis/ontology/provenance#ParameterSet> ; <https://w3id.org/modavis/ontology/provenance#parameterHash> "sha256:0000" .', "immutable parameter set requires"),
    ("unknown production method", 'ex:v a modvmi:VirtualInstrumentVersion ; modvmi:productionMethod ex:unknown .', "closed modavis 0.1.0 production-method scheme"),
    ("virtual instrument identity collapse", 'ex:x a modvmi:VirtualMusicalInstrument, modvmi:VirtualInstrumentProduct, modvmi:VirtualInstrumentVersion, modvmi:VirtualInstrumentPackage ; modinst:instrumentType insttype:virtual-musical-instrument ; modvmi:versionOfProduct ex:x ; modvmi:versionLabel "1.0" ; modvmi:implementsInstrument ex:x ; modvmi:packageOfVersion ex:x .', "cannot occupy more than one of the distinct virtual-instrument"),
    ("heritage recognition evidence mismatch", 'ex:r a modheritage:HeritageRecognition ; modheritage:hasEvidenceRelation ex:e . ex:e a modevidence:EvidenceRelation ; modevidence:evaluates ex:other .', "must identify that recognition"),
    ("heritage recognition supersession subject mismatch", 'ex:r1 a modheritage:HeritageRecognition ; modheritage:recognizesResource ex:instrument-a ; modheritage:supersedesRecognition ex:r2 . ex:r2 a modheritage:HeritageRecognition ; modheritage:recognizesResource ex:instrument-b .', "only a recognition of the same resource"),
    ("knowledge snapshot revision cycle", 'ex:a a modheritage:KnowledgeMaintenanceActivity ; modheritage:maintainedCollection ex:c ; modheritage:previousSnapshot ex:s1 ; modheritage:resultingSnapshot ex:s2 ; modheritage:addedAssertion ex:x . ex:b a modheritage:KnowledgeMaintenanceActivity ; modheritage:maintainedCollection ex:c ; modheritage:previousSnapshot ex:s2 ; modheritage:resultingSnapshot ex:s1 ; modheritage:addedAssertion ex:y . ex:s1 a modheritage:KnowledgeSnapshot ; modheritage:snapshotOfCollection ex:c ; modheritage:snapshotCreatedBy ex:b . ex:s2 a modheritage:KnowledgeSnapshot ; modheritage:snapshotOfCollection ex:c ; modheritage:snapshotCreatedBy ex:a .', "revision chain cannot contain a cycle"),
    ("knowledge snapshot reverse chronology", 'ex:a a modheritage:KnowledgeMaintenanceActivity ; modheritage:maintainedCollection ex:c ; modheritage:previousSnapshot ex:s1 ; modheritage:resultingSnapshot ex:s2 ; modheritage:addedAssertion ex:x . ex:s1 a modheritage:KnowledgeSnapshot ; modheritage:snapshotOfCollection ex:c ; modheritage:snapshotCreatedAt "2026-08-23T12:00:00Z"^^xsd:dateTime . ex:s2 a modheritage:KnowledgeSnapshot ; modheritage:snapshotOfCollection ex:c ; modheritage:snapshotCreatedBy ex:a ; modheritage:snapshotCreatedAt "2026-08-23T11:00:00Z"^^xsd:dateTime .', "creation time later than its previous snapshot"),
    ("knowledge snapshot timezone-less creation", 'ex:s a modheritage:KnowledgeSnapshot ; modheritage:snapshotCreatedAt "2026-08-27T12:00:00"^^xsd:dateTime .', "timezone-qualified xsd:datetime creation timestamp"),
    ("knowledge snapshot direct self-checksum", 'ex:s a modheritage:KnowledgeSnapshot ; modevidence:hasChecksum ex:c .', "must not carry a direct checksum"),
    ("historical review missing conclusion lineage", 'ex:r a modheritage:HistoricalClaimReview ; modheritage:producesAssertion ex:a . ex:a a modassert:Assertion .', "must identify the historical claim review as its generating activity"),
    ("context inverse mismatch", 'ex:a a modassert:Assertion ; modcontext:hasContextBinding ex:b . ex:b a modcontext:ContextBinding ; modcontext:contextualizesAssertion ex:other ; modcontext:dimension ex:d ; modcontext:contextRelation ex:applies ; modcontext:contextValue ex:v . ex:d a modcontext:ContextDimension .', "must identify that same assertion"),
    ("event evidence mismatch", 'ex:e a modevent:Event ; modevent:eventType eventtype:restoration ; modevent:affectedEntity ex:x ; modevent:hasSource ex:s ; modevent:evidencedBy ex:r . ex:r a modevidence:EvidenceRelation ; modevidence:evaluates ex:other .', "must identify that event"),
    ("event source mismatch", 'ex:e a modevent:Event ; modevent:eventType eventtype:restoration ; modevent:affectedEntity ex:x ; modevent:hasSource ex:s1 ; modevent:evidencedBy ex:r . ex:r a modevidence:EvidenceRelation ; modevidence:evaluates ex:e ; modevidence:usesFragment ex:f . ex:f modevidence:fragmentOf ex:ss . ex:ss modevidence:snapshotOf ex:s2 .', "event source must be the source resource"),
    ("source state mismatch", 'ex:r a modvmi:InstrumentSourceRelation ; modvmi:sourceRelationSubject ex:v ; modvmi:sourceInstrument ex:i ; modvmi:sourceState ex:s ; modvmi:sourceRelationType vmisource:sampled-from . ex:s a modinst:InstrumentState ; modinst:stateOf ex:other .', "source state must be a state"),
    ("source instrument wrong type", 'ex:v a modvmi:VirtualMusicalInstrument ; modinst:instrumentType insttype:virtual-musical-instrument . ex:not-instrument a modavis:Place . ex:r a modvmi:InstrumentSourceRelation ; modvmi:sourceRelationSubject ex:v ; modvmi:sourceInstrument ex:not-instrument ; modvmi:sourceRelationType vmisource:sampled-from .', "typed as a musical instrument"),
]


@pytest.mark.parametrize(("label", "body", "message"), CASES, ids=[case[0] for case in CASES])
def test_critical_constraint_negative_cases(label, body, message):
    data = Graph().parse(data=PREFIXES + body, format="turtle")
    conforms, _, report_text = validate(
        data,
        shacl_graph=load("shapes/*.ttl"),
        ont_graph=load("ontology/*.ttl") + load("vocab/*.ttl"),
        inference=None,
        advanced=True,
    )
    assert not conforms, label
    assert message in report_text.lower(), report_text
